# Generated by Django 5.2.1 on 2025-05-26 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория продукции',
                'verbose_name_plural': 'Категории продукции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('compatibility', models.CharField(max_length=255, verbose_name='Совместимость')),
                ('system', models.CharField(max_length=100, verbose_name='Система имплантации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xgate.productcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
