# Generated by Django 5.2.1 on 2025-05-28 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgate', '0002_order_promotion_supportrequest_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус: Активно'),
        ),
        migrations.CreateModel(
            name='viexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/')),
                ('is_public', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
